// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: battleship/active_games_by_user.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ActiveGamesByUser struct {
	Index string   `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Games []string `protobuf:"bytes,2,rep,name=games,proto3" json:"games,omitempty"`
}

func (m *ActiveGamesByUser) Reset()         { *m = ActiveGamesByUser{} }
func (m *ActiveGamesByUser) String() string { return proto.CompactTextString(m) }
func (*ActiveGamesByUser) ProtoMessage()    {}
func (*ActiveGamesByUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_e603a9977b92193e, []int{0}
}
func (m *ActiveGamesByUser) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveGamesByUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveGamesByUser.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveGamesByUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveGamesByUser.Merge(m, src)
}
func (m *ActiveGamesByUser) XXX_Size() int {
	return m.Size()
}
func (m *ActiveGamesByUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveGamesByUser.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveGamesByUser proto.InternalMessageInfo

func (m *ActiveGamesByUser) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ActiveGamesByUser) GetGames() []string {
	if m != nil {
		return m.Games
	}
	return nil
}

func init() {
	proto.RegisterType((*ActiveGamesByUser)(nil), "verstakgit.battleship.battleship.ActiveGamesByUser")
}

func init() {
	proto.RegisterFile("battleship/active_games_by_user.proto", fileDescriptor_e603a9977b92193e)
}

var fileDescriptor_e603a9977b92193e = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4d, 0x4a, 0x2c, 0x29,
	0xc9, 0x49, 0x2d, 0xce, 0xc8, 0x2c, 0xd0, 0x4f, 0x4c, 0x2e, 0xc9, 0x2c, 0x4b, 0x8d, 0x4f, 0x4f,
	0xcc, 0x4d, 0x2d, 0x8e, 0x4f, 0xaa, 0x8c, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0x52, 0x28, 0x4b, 0x2d, 0x2a, 0x2e, 0x49, 0xcc, 0x4e, 0xcf, 0x2c, 0xd1, 0x43, 0xe8,
	0x40, 0x62, 0x2a, 0xd9, 0x73, 0x09, 0x3a, 0x82, 0xf5, 0xbb, 0x83, 0xb4, 0x3b, 0x55, 0x86, 0x16,
	0xa7, 0x16, 0x09, 0x89, 0x70, 0xb1, 0x66, 0xe6, 0xa5, 0xa4, 0x56, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0x70, 0x06, 0x41, 0x38, 0x20, 0x51, 0xb0, 0x1d, 0x12, 0x4c, 0x0a, 0xcc, 0x20, 0x51, 0x30, 0xc7,
	0xc9, 0xf7, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0,
	0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x8c, 0xd3, 0x33, 0x4b,
	0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x11, 0xee, 0xd0, 0x47, 0x72, 0x79, 0x05, 0x32,
	0xa7, 0xa4, 0xb2, 0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x70, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x63, 0x46, 0x91, 0xe4, 0xe1, 0x00, 0x00, 0x00,
}

func (m *ActiveGamesByUser) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveGamesByUser) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveGamesByUser) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Games) > 0 {
		for iNdEx := len(m.Games) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Games[iNdEx])
			copy(dAtA[i:], m.Games[iNdEx])
			i = encodeVarintActiveGamesByUser(dAtA, i, uint64(len(m.Games[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintActiveGamesByUser(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintActiveGamesByUser(dAtA []byte, offset int, v uint64) int {
	offset -= sovActiveGamesByUser(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ActiveGamesByUser) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovActiveGamesByUser(uint64(l))
	}
	if len(m.Games) > 0 {
		for _, s := range m.Games {
			l = len(s)
			n += 1 + l + sovActiveGamesByUser(uint64(l))
		}
	}
	return n
}

func sovActiveGamesByUser(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozActiveGamesByUser(x uint64) (n int) {
	return sovActiveGamesByUser(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ActiveGamesByUser) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowActiveGamesByUser
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveGamesByUser: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveGamesByUser: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveGamesByUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveGamesByUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveGamesByUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Games", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowActiveGamesByUser
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthActiveGamesByUser
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthActiveGamesByUser
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Games = append(m.Games, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipActiveGamesByUser(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthActiveGamesByUser
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipActiveGamesByUser(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowActiveGamesByUser
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActiveGamesByUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowActiveGamesByUser
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthActiveGamesByUser
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupActiveGamesByUser
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthActiveGamesByUser
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthActiveGamesByUser        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowActiveGamesByUser          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupActiveGamesByUser = fmt.Errorf("proto: unexpected end of group")
)
